/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cpp.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cpp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.02, -0.16, 0]} rotation={[Math.PI / 2, 0, 1.66]} scale={[1.42, 2.65, 1.42]}>
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Text001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/cpp.glb')
